### ISSUE TITLE
Can't find the hash QmbzqL2F9S4T3mAMcgFWo1Jn63BTSmVBoGJp6ckdQsbZyf

### ISSUE THREAD

**Issue by Byte1122** [Leibniz137/DappnodePackage-block-explorer#1]
Maybe its me, or my IPFS configuration. But can't find the /ipfs/QmbzqL2F9S4T3mAMcgFWo1Jn63BTSmVBoGJp6ckdQsbZyf

**Comment by Leibniz137** [comment]
Use `QmauPMK5fa87yek2k42aes3x6x5kGSkkcVSCXGxPFodaS7` http://my.dappnode/#/installer/%2Fipfs%2FQmauPMK5fa87yek2k42aes3x6x5kGSkkcVSCXGxPFodaS7

I updated the README as well

**Comment by Byte1122** [comment]
@Leibniz137 thanks! Is it still based on Alethio?

> I updated the README as well

Which README do you mean?
